version: '3.4'

services:
  vikusdocker:
    # image: vikusdocker
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./data:/data

  redis:
    image: "redis:alpine"

  sharpsheet:
    build: ./services/sharpsheet
    volumes:
      - ./data:/data

  webserver:
    #image: nginx:alpine
    build: ./services/nginx
    ports:
      - 8000:8000
    volumes:
      - ./data:/usr/share/nginx/html/data
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
